config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

  end

  get '/users/:id/edit_profile_pic' => 'users#edit_profile_pic', as: 'edit_profile_pic'

  get '/users/:id/reservations' => 'reservations#user_reservations', as: 'user_reservations'
  get '/users/:id/listings' => 'listings#user_listings', as: 'user_listings'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'static/index'

  get 'static/home' => "static#home", as: "home"

  root 'static#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]

  end
  post 'listings/:id' => 'listings#verify', as: "verify"
  get '/listings/:id/upload_photos' => 'listings#upload_photos', as: 'upload_photos'

  get '/tags/:tag' => 'listings#index', as: "tag"

  resources :reservations , only: [:destroy] do
    resource :payments, only: [:new, :create]

  end

  resources :searches

end

app/models/listing.rb
require 'ffaker'

class Listing < ActiveRecord::Base

  # Associations
  belongs_to :user
  has_many :reservations, :dependent => :destroy

  validates :user, presence: true

  validates :title, presence: true
  validates :max_guests, presence: true
  validates :num_bedrooms, presence: true
  validates :price, presence: true
  validates :currency, presence: true


  acts_as_taggable # Alias for acts_as_taggable_on :tags
  # acts_as_taggable_on :skills, :interests

  mount_uploaders :photos, ImageUploader

  scope :city,          -> (city) { where(city: city) }
  scope :num_guests,    -> (num_guests) { where('max_guests >= ?', num_guests) }
  scope :num_bedrooms,  -> (num_bedrooms) { where('num_bedrooms >= ?', num_bedrooms) }
  scope :min_price,     -> (min_price) { where('price >= ?', min_price) }
  scope :max_price,     -> (max_price) { where('price <= ?', max_price) }

  include PgSearch
  pg_search_scope :search_by_keyword, :against => [:title, :description, :address, :house_rules]

  def tag_list
    self.tags.map { |t| t.name }.join(", ")
  end

  def tag_list=(new_value)
    tag_names = new_value.split(/,\s+/)
    self.tags = tag_names.map { |name| ActsAsTaggableOn::Tag.where('name = ?', name).first or ActsAsTaggableOn::Tag.create(:name => name) }
  end


  def self.populate

    5.times do |n|
     title =  FFaker::Movie.title
     description =  FFaker::HipsterIpsum.sentence
     address = FFaker::AddressUS.street_address
     country  = FFaker::AddressUS.country
     phone = FFaker::PhoneNumber.phone_number
     num_bedrooms =  (rand * 3).to_i
     price = (rand * 100).to_i
     currency = "USD"
     house_rules = FFaker::HipsterIpsum.paragraph

     listing = Listing.create!(
       title: title,
       description: description,
       address: address,
       country: country,
       phone: phone,
       num_bedrooms: num_bedrooms,
       price: price,
       currency: currency,
       house_rules: house_rules
     )
     listing.tag_list = FFaker::CheesyLingo.word

    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login

  def index
    if params[:tag]
      @listing = Listing.new
      @listings = Listing.tagged_with(params[:tag]).order(created_at: :asc).page(params[:page]).per_page(10)
    else
      @listing = Listing.new
      @listings = Listing.all.order(created_at: :asc).page(params[:page]).per_page(10)
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @reservation = @listing.reservations.new
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    # @listing.tag_list = listing_params[:tag_list].split(',')

    if @listing.save

      redirect_to user_listings_path(current_user), notice: "Your listing has been created"
    else
      flash[:alert] = "Your listing is not created"
      render 'new'
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update_attributes(listing_params)
      # redirect_to action: 'show', id: @listing.id
      redirect_to listing_path(@listing), notice: "Listing has been updated"
    else
      # redirect_to listing_path(@listing), alert: "System error, cannot update your listing"
      flash[:alert] = "System error, cannot update your listing"
      render 'edit'
    end

  end

  def destroy
    Listing.find(params[:id]).destroy
    # redirect_to action: 'index'
    redirect_to listings_path, notice: "Your listing has been deleted."
  end

  def verify
    @listing = Listing.find(params[:id])
    @listing.verified ^= true
    @listing.save

    # redirect_to action: 'show', id: @listing.id
    redirect_to listing_path(@listing)
  end

  def upload_photos
    @listing = Listing.find(params[:id])

  end

  def user_listings
    @listings = User.find(params[:id]).listings
  end

  private
  def listing_params
    params.require(:listing).permit(:title, :description, :address, :country, :phone, :num_bedrooms, :price, :currency, :house_rules, :tag_list, :verified, {photos: []}, :city, :country_code, :max_guests)
  end



end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb


<div class="form-group">
  <%= form.label :title, 'Title', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :title , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :description, 'Description', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_area :description, size: '50x8' , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :address, 'Address', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :address , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :city, 'City', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :city , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :country, 'Country', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :country , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :phone, 'Phone', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :phone , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :max_guests, 'Max guests', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :max_guests , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :num_bedrooms, 'Num of Bedrooms', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :num_bedrooms , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :price, 'Price', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :price , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :currency, 'Currency', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :currency , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :house_rules, 'House Rules', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_area :house_rules, size: '50x5' , class: 'form-control'%>
  </div>
</div>

<div class="form-group">
  <%= form.label :tag_list, 'Tags (separated by commas)', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :tag_list , class: 'form-control'%>
  </div>
</div>

<!--
<div class="form-group">
  <%= form.label :verified, 'Verify', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.check_box :verified %>
  </div>
</div>
 -->

app/views/listings/_form_upload_photos.html.erb

<div class="form-group">
  <%= form.label :photos, 'Photos', class:'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <p class="help-block">You can upload multiple photos.</p>
    <%= form.file_field :photos, multiple: true %>

  </div>
</div>

app/views/listings/_photos.html.erb

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @listing.photos.each_with_index do |data, i| %>
      <li data-target="#carousel-example-generic" data-slide-to="#{i}" class="#{'active' if i == 0}"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @listing.photos.each_with_index do |photo, i| %>
        <% if i == 0 %>
          <div class="item active">
        <% else %>
          <div class="item">
        <% end %>

        <%= image_tag photo.medium.url %>

        <div class="carousel-caption">
          <%= photo.identifier %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/listings/_verify.html.erb
<% if listing.verified? %>
  <%= image_tag("verified.jpg", alt: "Verified!") %>
<% end %>

app/views/listings/edit.html.erb
<div class='container'>

<h2>Edit Listing</h2>

<%= form_for @listing, html: {class: 'form-horizontal'} do |form| %>
  <%= render partial: '/listings/form', object: form %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit 'Save changes!' %>
    </div>
  </div>

<% end %>


<%= link_to 'Back', '/listings' %>

</div>

app/views/listings/index.html.erb
<div class="container">

<h2>Listing index</h2>

<%= link_to 'Create new Listing', '/listings/new' %>

<%= form_for @listing, url: listings_path, html: {method: 'get', class: 'form-horizontal'} do |form| %>

  <div class="form-group">
    <%= form.label :city, 'City', class:'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= form.select :city , ['Malang', 'Ann Arbor'], class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit 'Search' %>
    </div>
  </div>

<% end %>



<h3><%= link_to "Listings", listings_path %></h3>

<div id="tag_cloud">
  <% tag_cloud Listing.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<% if @listings.blank? %>
  <p>
    There is no listing yet
  </p>
<% else %>
  <div class="flickr_pagination">
    <%= will_paginate @listings, previous_label: h("<"), next_label: h(">") %>
  </div>

  <p>
    <strong>Total listings: </strong><%= @listings.count %>
  </p>

  <ul id='listings'>
    <% @listings.each do |listing| %>
      <li>
        <% if listing.photos.count > 0 %>
          <p><%= image_tag listing.photos[0].thumb.url, class: "img-rounded" %></p>
        <% end %>
        <%= render partial: '/listings/verify', locals: {listing: listing} %>
        <%= link_to listing.title, listing %>
      </li>
    <% end %>
  </ul>


<% end %>


<p><%= link_to 'Back', root_path %></p>


</div>

app/views/listings/new.html.erb
<div class="container">

<h2>Create New Listing</h2>

<%= form_for @listing, html: {class: 'form-horizontal'} do |form| %>
  <%= render partial: '/listings/form', object: form %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit 'Create!' %>
    </div>
  </div>

<% end %>

<%= link_to 'Back', '/listings' %>


</div>

app/views/listings/show.html.erb
<div class='container'>
  <h2>Listing details</h2>

<p>
  <b>
    <% if allow?("listings", "edit", @listing.id) %>
      <%= link_to 'Edit', edit_listing_path(@listing) %>
    <% end %>

    <% if allow?("listings", "destroy", @listing.id) %>
      <%= link_to 'Delete', @listing, method: :delete, data: {confirm: "Are you sure you want to delete this listing?"} %>
    <% end %>
  </b>

</p>
<p>
  <br>
  <% if allow?("listings", "verify", @listing.id) %>

    <% if @listing.verified? %>
      <%= link_to 'Unverify', verify_path(@listing), method: :post, data: {confirm: "Are you sure you want to UN-verify this listing?"} %>
    <% else %>
      <%= link_to 'Verify', verify_path(@listing), method: :post, data: {confirm: "Are you sure you want to verify this listing?"} %>
    <% end %>

  <% end %>
</p>

<p>
  <%= link_to 'Upload Photos', upload_photos_path(@listing) %>
</p>

<%= render "/reservations/form" %>

<% if @reservation.errors.full_messages.present? %>
  <div>
    <%= @reservation.errors.full_messages %>
  </div>
<% end %>


<% if @listing.photos.count > 0 %>
  <%= render partial: '/listings/photos', object: @listing %>
<% end %>

<p>
  <strong><%= @listing.title %></strong>
  <%= render partial: '/listings/verify', locals: {listing: @listing} %>
</p>

<p>
  <strong>Description: </strong>
  <pre>
    <%= @listing.description %>
  </pre>
</p>

<p>
  <strong>Address: </strong>
  <%= @listing.address %>
</p>
<p>
  <strong>City: </strong>
  <%= @listing.city %>
</p>
<p>
  <strong>Country: </strong>
  <%= @listing.country %>
</p>
<p>
  <strong>Phone: </strong>
  <%= @listing.phone %>
</p>
<p>
  <strong>Max guests: </strong>
  <%= @listing.max_guests %>
</p>
<p>
  <strong>Num of Bedrooms: </strong>
  <%= @listing.num_bedrooms %>
</p>
<p>
  <strong>Price: </strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Currency: </strong>
  <%= @listing.currency %>
</p>

<p>
  <strong>House Rules: </strong>
  <pre>
    <%= @listing.house_rules %>
  </pre>
</p>

<p>
  Tags: <%= raw @listing.tag_list.split(/,\s+/).map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>

<p>
  <h3>Reservations</h3>
  <p>Total: <%= @listing.reservations.count %></p>

  <% @listing.reservations.order(start_date: :asc).each do |r| %>
    <p> <%= r.user.email %> Start <%= r.start_date %>, End <%= r.end_date %>, num guests <%= r.num_guests %> </p>
  <% end %>
</p>


<p>
  <%= link_to 'Back', '/listings' %>
</p>

</div>

app/views/listings/upload_photos.html.erb
<div class='container'>

<h2>Upload Listing Photos</h2>

<%= form_for @listing, html: {class: 'form-horizontal', multipart: true} do |form| %>
  <%= render partial: '/listings/form_upload_photos', locals: {form: form} %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit 'Save changes!' %>
    </div>
  </div>

<% end %>


<%= link_to 'Back', '/listings' %>

</div>

app/views/listings/user_listings.html.erb
<div class='container'>


<h2>My Listings</h2>

<p>Total: <%= @listings.count %></p>

<% @listings.order(created_at: :asc).each do |r| %>
  <p> <%= link_to r.title, r %> </p>
<% end %>



<p><%= link_to 'Back', root_path %></p>


</div>