config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

  end

  get '/users/:id/edit_profile_pic' => 'users#edit_profile_pic', as: 'edit_profile_pic'

  get '/users/:id/reservations' => 'reservations#user_reservations', as: 'user_reservations'
  get '/users/:id/listings' => 'listings#user_listings', as: 'user_listings'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'static/index'

  get 'static/home' => "static#home", as: "home"

  root 'static#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]

  end
  post 'listings/:id' => 'listings#verify', as: "verify"
  get '/listings/:id/upload_photos' => 'listings#upload_photos', as: 'upload_photos'

  get '/tags/:tag' => 'listings#index', as: "tag"

  resources :reservations , only: [:destroy] do
    resource :payments, only: [:new, :create]

  end

  resources :searches

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :reservation

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    # calculate amount

    @reservation = Reservation.find(params[:reservation_id])
    @days = @reservation.end_date.mjd - @reservation.start_date.mjd
    @amount = @days * @reservation.listing.price
    @client_token = Braintree::ClientToken.generate
  end

  def create
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
      :amount => get_amount(params[:reservation_id]),
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
    )

    byebug
    if result.success?

      #update reservation status to paid
      @reservation = Reservation.find(params[:reservation_id])
      # @reservation.paid = true
      # @reservation.save
      @reservation.update(paid: true)

      byebug

      #insert success transaction to payments table
      @payment = Payment.new(
      cardholder_name: params[:checkout_form][:cardholder_name], billing_address: params[:checkout_form][:billing_address], billing_postal_code: params[:checkout_form][:billing_postal_code], transaction_id: result.transaction.id,
      card_type: result.transaction.credit_card_details.card_type,
      amount: result.transaction.amount
        )
      @payment.reservation_id = params[:reservation_id]
      @payment.save

      byebug

      redirect_to user_reservations_path(current_user), :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

  private
  def payment_params
    params.require(:payment).permit(:transaction_id, :amount, :card_type, :cardholder_name, :billing_address, :billing_postal_code, :reservation_id)
  end

  def get_amount(reservation_id)
    reservation = Reservation.find(reservation_id)
    (reservation.end_date.mjd - reservation.start_date.mjd) * reservation.listing.price
  end



end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<div class='container'>


<h2>Payment</h2>

<p> Start date: <%= @reservation.start_date %> </p>
<p> End   date: <%= @reservation.end_date %> </p>
<p> Total: <%= @days %> days</p>
<p> Price per night: <%= @reservation.listing.price %> <%= @reservation.listing.currency %></p>
<p> Amount = <%= @amount %> <%= @reservation.listing.currency %> </p>


<div class="panel panel-default bootstrap-basic">
  <div class="panel-heading">
    <h3 class="panel-title">Enter Card Details</h3>
  </div>

  <%= form_for :checkout_form, url: reservation_payments_path(@reservation.id), html: {id: "cardForm", class: 'panel-body form-horizontal' } do |form| %>

  <div class="row">

    <div class="form-group">
      <%= form.label :cardholder_name, 'Cardholder name', class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :cardholder_name , class: 'hosted-field col-sm-6'%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :billing_address, 'Billing Address', class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :billing_address , class: 'hosted-field col-sm-6'%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :billing_postal_code, 'Billing Postal Code', class:'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.text_field :billing_postal_code , class: 'hosted-field'%>
      </div>
    </div>


  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"}  %>
  <div id="card-number" class="hosted-field"></div>


  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field :payment_method_nonce %>

  <div class ="button-container">
    <%= form.submit "Pay now", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
  </div>

  <% end %>
</div>

</div>

</div> <!-- end of container -->


<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>



<script>

var form = document.querySelector('#cardForm');
// var authorization = 'sandbox_g42y39zw_348pk9cgf3bgyw2b';
var authorization = '<%= @client_token %>';
var submitBtn = document.querySelector("#submit-payment-btn");

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submitBtn.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment-method-nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('#checkout_form_payment_method_nonce').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});


</script>