config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

  end

  get '/users/:id/edit_profile_pic' => 'users#edit_profile_pic', as: 'edit_profile_pic'

  get '/users/:id/reservations' => 'reservations#user_reservations', as: 'user_reservations'
  get '/users/:id/listings' => 'listings#user_listings', as: 'user_listings'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'static/index'

  get 'static/home' => "static#home", as: "home"

  root 'static#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]

  end
  post 'listings/:id' => 'listings#verify', as: "verify"
  get '/listings/:id/upload_photos' => 'listings#upload_photos', as: 'upload_photos'

  get '/tags/:tag' => 'listings#index', as: "tag"

  resources :reservations , only: [:destroy] do
    resource :payments, only: [:new, :create]

  end

  resources :searches

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @cities = Listing.uniq.pluck(:city)

  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])

    @listings = Listing.all.order(created_at: :asc).page(params[:page]).per_page(10)
    @listings = @listings.search_by_keyword(@search.keyword) if @search.keyword.present?
    @listings = @listings.city(@search.city) if @search.city.present?
    @listings = @listings.num_bedrooms(@search.num_bedrooms) if @search.num_bedrooms.present?
    @listings = @listings.num_guests(@search.num_guests) if @search.num_guests.present?
    @listings = @listings.min_price(@search.min_price) if @search.min_price.present?
    @listings = @listings.max_price(@search.max_price) if @search.max_price.present?

  end

  private
  def search_params
    params.require(:search).permit(:keyword, :city, :country, :min_price, :max_price, :num_bedrooms, :num_guests)
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<div class="container">

<h2>Search Listings</h2>

<%= form_for @search, html: {class: 'form-horizontal'} do |form| %>

<div class="form-group">
  <%= form.label :keyword, 'Keyword', class:'col-sm-2 control-label' %>
  <div class="col-sm-3">
    <%= form.text_field :keyword , class: 'form-control'%>
  </div>
</div>


  <div class="form-group">
    <%= form.label :city, 'City', class:'col-sm-2 control-label' %>
    <div class="col-sm-5">
      <%= form.select :city , options_for_select(@cities), class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :num_bedrooms, 'Number of Bedrooms', class:'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= form.number_field :num_bedrooms , class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :num_guests, 'Number of Guests', class:'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= form.number_field :num_guests , class: 'form-control'%>
    </div>
  </div>


  <div class="form-group">
    <%= form.label :min_price, 'Min Price', class:'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= form.number_field :min_price , class: 'form-control'%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :max_price, 'Max Price', class:'col-sm-2 control-label' %>
    <div class="col-sm-3">
      <%= form.number_field :max_price , class: 'form-control'%>
    </div>
  </div>



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit 'Search' %>
    </div>
  </div>

<% end %>



<%= link_to 'Back', listings_path %>


</div>

app/views/searches/show.html.erb
<div class="container">

<h2>Listing index</h2>


<% if @listings.blank? %>
  <p>
    Sorry, no matches.
  </p>
<% else %>
  <div id="tag_cloud">
    <% tag_cloud @listings.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>

  <p>
    <strong>Total listings: </strong><%= @listings.count %>
  </p>

  <div class="flickr_pagination">
    <%= will_paginate @listings, previous_label: h("<"), next_label: h(">") %>
  </div>


  <ul id='listings'>
    <% @listings.each do |listing| %>
      <li>
        <% if listing.photos.count > 0 %>
          <p><%= image_tag listing.photos[0].thumb.url, class: "img-rounded" %></p>
        <% end %>
        <%= render partial: '/listings/verify', locals: {listing: listing} %>
        <%= link_to listing.title, listing %>
      </li>
    <% end %>
  </ul>


<% end %>

<p><%= link_to 'Back', new_search_path %></p>