config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]

  end

  get '/users/:id/edit_profile_pic' => 'users#edit_profile_pic', as: 'edit_profile_pic'

  get '/users/:id/reservations' => 'reservations#user_reservations', as: 'user_reservations'
  get '/users/:id/listings' => 'listings#user_listings', as: 'user_listings'

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'static/index'

  get 'static/home' => "static#home", as: "home"

  root 'static#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings do
    resources :reservations, only: [:create]

  end
  post 'listings/:id' => 'listings#verify', as: "verify"
  get '/listings/:id/upload_photos' => 'listings#upload_photos', as: 'upload_photos'

  get '/tags/:tag' => 'listings#index', as: "tag"

  resources :reservations , only: [:destroy] do
    resource :payments, only: [:new, :create]

  end

  resources :searches

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rudynb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


  <!-- <%= javascript_include_tag 'application' %> -->
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render template: '/static/nav' %>


  <div id="header">
    <% if signed_in? %>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else %>
      <!-- <%= link_to t(".sign_in"), sign_in_path %> -->

      <button type="button" class="btn btn-success pull-left" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-modal-window" aria-hidden="true"></span> Sign in now</button>
      <%= render template: '/static/modal_signin' %>

    <% end %>
  </div>

  <div id="flash">
    <% flash.each do |key, value| %>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>